name = "garden-house"
compatibility_date = "2024-09-23"
pages_build_output_dir = "frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "garden-house-db"
database_id = "88033147-3211-4099-af82-e3c2a3fb2957"
